# Use Nginx as the base image
FROM nginx:latest

# Copy all frontend files (HTML, CSS, JS) to the default nginx html directory
COPY . /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Start Nginx in the foreground
CMD ["nginx", "-g", "daemon off;"]

